spring:
  application:
  name: delivery_app

---
spring:
  datasource:
    url: jdbc:mysql://${DB_URL}/delivery
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      encoding: UTF-8

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #show_sql: true
        format_sql: true
        connection:
          CharSet: utf-8
          characterEncoding: utf-8
          useUnicode: true

logging.level:
  root: info
